name: Dart

on:
  push:
    branches: 
      - '**' 
  pull_request:
    branches: 
      - '**' 
  release: 
    types: [created]

jobs:
  build_teste:
    if: github.event_name != 'release'
    name: Build Flutter Homologacao (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter clean
    - run: flutter test
    - run: flutter build appbundle

  build_producao:
    if: github.event_name == 'release'
    name: Build Flutter Producao (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter clean
    - run: flutter test
    - run: flutter build appbundle --obfuscate --split-debug-info=symbols/Android
    - run: cp symbols/Android -r symbols/iOS
    - name: Upload Symbols Android
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORIES_KEY }}
      with:
        asset_paths: '["./symbols/Android/*", "./symbols/iOS/*"]'
