name: Dart

on:
  push:
    branches: 
      - '**' 
  pull_request:
    branches: 
      - '**' 
  release: 
    types: [created]

jobs:
  build_teste:
    if: github.event_name != 'release'
    name: Build Flutter Homologacao (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter clean
    - run: flutter test
    - run: flutter build appbundle

  build_producao:
    if: github.event_name == 'release'
    name: Build Flutter Producao (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter clean
    - run: flutter test
    - run: flutter build appbundle --obfuscate --split-debug-info=symbols/Android
    - run: mkdir symbols/iOS/
    - run: cp symbols/Android/* symbols/iOS/
    - name: Compact Release Files
      uses: thedoctor0/zip-release@master
      with:
        filename: 'symbols.zip'
        path: './symbols'
    - run: rm -r ./symbols
    - run: mkdir symbols
    - run: mv symbols.zip symbols/
    - name: Upload Symbols Android
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'symbols/*'
        repo-token: ${{ secrets.REPOSITORIES_KEY }}