name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build_appbundle:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter clean
    - run: flutter test
    - run: flutter build appbundle --obfuscate --split-debug-info=symbols
    - name: Upload Symbols Android
    id: upload-release-asset 
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ secrets.REPOSITORIES_KEY }}
    with:
      asset_path: symbols
      asset_name: symbols
      asset_content_type: application/zip